import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>Photos | Joeyui.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p className="text-3xl">Photos app coming soon</p>
        </div>
      </main>
    </>
  );
}

export default Home;
